/* ============================================================================
   FomAI Office — Localization file
   Автоматически подгружается при первом запуске приложения.
   Формат: window.FOMAI_LOCALES = { code: { n: name, f: flag, s: strings } }
   Ключи строк:
     brand   — название продукта
     tag     — слоган
     home    — Главная
     files   — Файлы
     create  — Создать
     open    — Открыть
     save    — Сохранить
     close   — Закрыть
     stng    — Настройки
     lang    — Язык
     search  — Поиск
     tools   — Инструменты
     about   — О проекте
     cancel  — Отмена
     welcome — Добро пожаловать
   ============================================================================ */
window.FOMAI_LOCALES = {

/* ═══════════════════ РЕАЛЬНЫЕ ЯЗЫКИ (93) ═══════════════════ */

en:{n:'English',f:'🇬🇧',s:{brand:'FomAI Office',tag:'Office suite in your browser',home:'Home',files:'Files',create:'Create',open:'Open',save:'Save',close:'Close',stng:'Settings',lang:'Language',search:'Search',tools:'Tools',about:'About',cancel:'Cancel',welcome:'Welcome'}},
ru:{n:'Русский',f:'🇷🇺',s:{brand:'FomAI Office',tag:'Офисный пакет в браузере',home:'Главная',files:'Файлы',create:'Создать',open:'Открыть',save:'Сохранить',close:'Закрыть',stng:'Настройки',lang:'Язык',search:'Поиск',tools:'Инструменты',about:'О проекте',cancel:'Отмена',welcome:'Добро пожаловать'}},
uk:{n:'Українська',f:'🇺🇦',s:{brand:'FomAI Office',tag:'Офісний пакет у браузері',home:'Головна',files:'Файли',create:'Створити',open:'Відкрити',save:'Зберегти',close:'Закрити',stng:'Налаштування',lang:'Мова',search:'Пошук',tools:'Інструменти',about:'Про проєкт',cancel:'Скасувати',welcome:'Вітаємо'}},
be:{n:'Беларуская',f:'🇧🇾',s:{brand:'FomAI Office',tag:'Офісны пакет у браўзеры',home:'Галоўная',files:'Файлы',create:'Стварыць',open:'Адкрыць',save:'Захаваць',close:'Закрыць',stng:'Налады',lang:'Мова',search:'Пошук',tools:'Інструменты',about:'Пра праект',cancel:'Скасаваць',welcome:'Вітаем'}},
pl:{n:'Polski',f:'🇵🇱',s:{brand:'FomAI Office',tag:'Pakiet biurowy w przeglądarce',home:'Główna',files:'Pliki',create:'Utwórz',open:'Otwórz',save:'Zapisz',close:'Zamknij',stng:'Ustawienia',lang:'Język',search:'Szukaj',tools:'Narzędzia',about:'O projekcie',cancel:'Anuluj',welcome:'Witaj'}},
cs:{n:'Čeština',f:'🇨🇿',s:{brand:'FomAI Office',tag:'Kancelářský balík v prohlížeči',home:'Domů',files:'Soubory',create:'Vytvořit',open:'Otevřít',save:'Uložit',close:'Zavřít',stng:'Nastavení',lang:'Jazyk',search:'Hledat',tools:'Nástroje',about:'O projektu',cancel:'Zrušit',welcome:'Vítejte'}},
sk:{n:'Slovenčina',f:'🇸🇰',s:{brand:'FomAI Office',tag:'Kancelársky balík v prehliadači',home:'Domov',files:'Súbory',create:'Vytvoriť',open:'Otvoriť',save:'Uložiť',close:'Zavrieť',stng:'Nastavenia',lang:'Jazyk',search:'Hľadať',tools:'Nástroje',about:'O projekte',cancel:'Zrušiť',welcome:'Vitajte'}},
bg:{n:'Български',f:'🇧🇬',s:{brand:'FomAI Office',tag:'Офис пакет в браузъра',home:'Начало',files:'Файлове',create:'Създай',open:'Отвори',save:'Запази',close:'Затвори',stng:'Настройки',lang:'Език',search:'Търси',tools:'Инструменти',about:'Относно',cancel:'Отказ',welcome:'Добре дошъл'}},
sr:{n:'Српски',f:'🇷🇸',s:{brand:'FomAI Office',tag:'Канцеларијски пакет у прегледачу',home:'Почетна',files:'Датотеке',create:'Направи',open:'Отвори',save:'Сачувај',close:'Затвори',stng:'Подешавања',lang:'Језик',search:'Претрага',tools:'Алати',about:'О пројекту',cancel:'Откажи',welcome:'Добро дошао'}},
hr:{n:'Hrvatski',f:'🇭🇷',s:{brand:'FomAI Office',tag:'Uredski paket u pregledniku',home:'Početna',files:'Datoteke',create:'Stvori',open:'Otvori',save:'Spremi',close:'Zatvori',stng:'Postavke',lang:'Jezik',search:'Pretraži',tools:'Alati',about:'O projektu',cancel:'Odustani',welcome:'Dobro došao'}},
sl:{n:'Slovenščina',f:'🇸🇮',s:{brand:'FomAI Office',tag:'Pisarniški paket v brskalniku',home:'Domov',files:'Datoteke',create:'Ustvari',open:'Odpri',save:'Shrani',close:'Zapri',stng:'Nastavitve',lang:'Jezik',search:'Iskanje',tools:'Orodja',about:'O projektu',cancel:'Prekliči',welcome:'Dobrodošli'}},
bs:{n:'Bosanski',f:'🇧🇦',s:{brand:'FomAI Office',tag:'Kancelarijski paket u pregledniku',home:'Početna',files:'Datoteke',create:'Napravi',open:'Otvori',save:'Sačuvaj',close:'Zatvori',stng:'Postavke',lang:'Jezik',search:'Pretraga',tools:'Alati',about:'O projektu',cancel:'Otkaži',welcome:'Dobro došli'}},
mk:{n:'Македонски',f:'🇲🇰',s:{brand:'FomAI Office',tag:'Канцелариски пакет во прелистувач',home:'Дома',files:'Датотеки',create:'Создај',open:'Отвори',save:'Зачувај',close:'Затвори',stng:'Поставки',lang:'Јазик',search:'Пребарај',tools:'Алатки',about:'За проектот',cancel:'Откажи',welcome:'Добредојде'}},
sq:{n:'Shqip',f:'🇦🇱',s:{brand:'FomAI Office',tag:'Paketë zyre në shfletues',home:'Kryefaqja',files:'Skedarë',create:'Krijo',open:'Hap',save:'Ruaj',close:'Mbyll',stng:'Cilësimet',lang:'Gjuha',search:'Kërko',tools:'Mjete',about:'Rreth',cancel:'Anulo',welcome:'Mirë se vjen'}},
ro:{n:'Română',f:'🇷🇴',s:{brand:'FomAI Office',tag:'Pachet office în browser',home:'Acasă',files:'Fișiere',create:'Creează',open:'Deschide',save:'Salvează',close:'Închide',stng:'Setări',lang:'Limbă',search:'Caută',tools:'Unelte',about:'Despre',cancel:'Anulează',welcome:'Bine ai venit'}},
hu:{n:'Magyar',f:'🇭🇺',s:{brand:'FomAI Office',tag:'Irodai csomag böngészőben',home:'Főoldal',files:'Fájlok',create:'Létrehozás',open:'Megnyitás',save:'Mentés',close:'Bezárás',stng:'Beállítások',lang:'Nyelv',search:'Keresés',tools:'Eszközök',about:'Névjegy',cancel:'Mégse',welcome:'Üdv'}},
el:{n:'Ελληνικά',f:'🇬🇷',s:{brand:'FomAI Office',tag:'Σουίτα γραφείου στον browser',home:'Αρχική',files:'Αρχεία',create:'Δημιουργία',open:'Άνοιγμα',save:'Αποθήκευση',close:'Κλείσιμο',stng:'Ρυθμίσεις',lang:'Γλώσσα',search:'Αναζήτηση',tools:'Εργαλεία',about:'Σχετικά',cancel:'Άκυρο',welcome:'Καλώς ήρθατε'}},
tr:{n:'Türkçe',f:'🇹🇷',s:{brand:'FomAI Office',tag:'Tarayıcıda ofis paketi',home:'Ana sayfa',files:'Dosyalar',create:'Oluştur',open:'Aç',save:'Kaydet',close:'Kapat',stng:'Ayarlar',lang:'Dil',search:'Ara',tools:'Araçlar',about:'Hakkında',cancel:'İptal',welcome:'Hoş geldiniz'}},
az:{n:'Azərbaycan',f:'🇦🇿',s:{brand:'FomAI Office',tag:'Brauzerdə ofis paketi',home:'Əsas',files:'Fayllar',create:'Yarat',open:'Aç',save:'Yadda saxla',close:'Bağla',stng:'Parametrlər',lang:'Dil',search:'Axtar',tools:'Alətlər',about:'Haqqında',cancel:'Ləğv',welcome:'Xoş gəldin'}},
hy:{n:'Հայերեն',f:'🇦🇲',s:{brand:'FomAI Office',tag:'Գրասենյակային փաթեթ',home:'Գլխավոր',files:'Ֆայլեր',create:'Ստեղծել',open:'Բացել',save:'Պահել',close:'Փակել',stng:'Կարգավորումներ',lang:'Լեզու',search:'Փնտրել',tools:'Գործիքներ',about:'Մասին',cancel:'Չեղարկել',welcome:'Բարի գալուստ'}},
ka:{n:'ქართული',f:'🇬🇪',s:{brand:'FomAI Office',tag:'საოფისე პაკეტი ბრაუზერში',home:'მთავარი',files:'ფაილები',create:'შექმნა',open:'გახსნა',save:'შენახვა',close:'დახურვა',stng:'პარამეტრები',lang:'ენა',search:'ძებნა',tools:'ხელსაწყოები',about:'შესახებ',cancel:'გაუქმება',welcome:'მოგესალმებით'}},
de:{n:'Deutsch',f:'🇩🇪',s:{brand:'FomAI Office',tag:'Office-Paket im Browser',home:'Startseite',files:'Dateien',create:'Erstellen',open:'Öffnen',save:'Speichern',close:'Schließen',stng:'Einstellungen',lang:'Sprache',search:'Suchen',tools:'Werkzeuge',about:'Über',cancel:'Abbrechen',welcome:'Willkommen'}},
nl:{n:'Nederlands',f:'🇳🇱',s:{brand:'FomAI Office',tag:'Officepakket in de browser',home:'Startpagina',files:'Bestanden',create:'Aanmaken',open:'Openen',save:'Opslaan',close:'Sluiten',stng:'Instellingen',lang:'Taal',search:'Zoeken',tools:'Hulpmiddelen',about:'Over',cancel:'Annuleren',welcome:'Welkom'}},
af:{n:'Afrikaans',f:'🇿🇦',s:{brand:'FomAI Office',tag:'Kantoorpakket in die blaaier',home:'Tuis',files:'Lêers',create:'Skep',open:'Maak oop',save:'Stoor',close:'Maak toe',stng:'Instellings',lang:'Taal',search:'Soek',tools:'Gereedskap',about:'Oor',cancel:'Kanselleer',welcome:'Welkom'}},
sv:{n:'Svenska',f:'🇸🇪',s:{brand:'FomAI Office',tag:'Kontorspaket i webbläsaren',home:'Hem',files:'Filer',create:'Skapa',open:'Öppna',save:'Spara',close:'Stäng',stng:'Inställningar',lang:'Språk',search:'Sök',tools:'Verktyg',about:'Om',cancel:'Avbryt',welcome:'Välkommen'}},
no:{n:'Norsk',f:'🇳🇴',s:{brand:'FomAI Office',tag:'Kontorpakke i nettleseren',home:'Hjem',files:'Filer',create:'Opprett',open:'Åpne',save:'Lagre',close:'Lukk',stng:'Innstillinger',lang:'Språk',search:'Søk',tools:'Verktøy',about:'Om',cancel:'Avbryt',welcome:'Velkommen'}},
da:{n:'Dansk',f:'🇩🇰',s:{brand:'FomAI Office',tag:'Kontorpakke i browseren',home:'Hjem',files:'Filer',create:'Opret',open:'Åbn',save:'Gem',close:'Luk',stng:'Indstillinger',lang:'Sprog',search:'Søg',tools:'Værktøjer',about:'Om',cancel:'Annuller',welcome:'Velkommen'}},
is:{n:'Íslenska',f:'🇮🇸',s:{brand:'FomAI Office',tag:'Skrifstofupakki í vafranum',home:'Heim',files:'Skrár',create:'Búa til',open:'Opna',save:'Vista',close:'Loka',stng:'Stillingar',lang:'Tungumál',search:'Leita',tools:'Verkfæri',about:'Um',cancel:'Hætta við',welcome:'Velkomin'}},
fi:{n:'Suomi',f:'🇫🇮',s:{brand:'FomAI Office',tag:'Toimistopaketti selaimessa',home:'Koti',files:'Tiedostot',create:'Luo',open:'Avaa',save:'Tallenna',close:'Sulje',stng:'Asetukset',lang:'Kieli',search:'Haku',tools:'Työkalut',about:'Tietoja',cancel:'Peruuta',welcome:'Tervetuloa'}},
et:{n:'Eesti',f:'🇪🇪',s:{brand:'FomAI Office',tag:'Kontoripakett brauseris',home:'Avaleht',files:'Failid',create:'Loo',open:'Ava',save:'Salvesta',close:'Sulge',stng:'Seaded',lang:'Keel',search:'Otsi',tools:'Tööriistad',about:'Teave',cancel:'Tühista',welcome:'Tere tulemast'}},
lv:{n:'Latviešu',f:'🇱🇻',s:{brand:'FomAI Office',tag:'Biroja pakotne pārlūkā',home:'Sākums',files:'Faili',create:'Izveidot',open:'Atvērt',save:'Saglabāt',close:'Aizvērt',stng:'Iestatījumi',lang:'Valoda',search:'Meklēt',tools:'Rīki',about:'Par',cancel:'Atcelt',welcome:'Laipni lūdzam'}},
lt:{n:'Lietuvių',f:'🇱🇹',s:{brand:'FomAI Office',tag:'Biuro paketas naršyklėje',home:'Pradžia',files:'Failai',create:'Sukurti',open:'Atidaryti',save:'Išsaugoti',close:'Uždaryti',stng:'Nustatymai',lang:'Kalba',search:'Ieškoti',tools:'Įrankiai',about:'Apie',cancel:'Atšaukti',welcome:'Sveiki'}},
ga:{n:'Gaeilge',f:'🇮🇪',s:{brand:'FomAI Office',tag:'Pacáiste oifige sa bhrabhsálaí',home:'Baile',files:'Comhaid',create:'Cruthaigh',open:'Oscail',save:'Sábháil',close:'Dún',stng:'Socruithe',lang:'Teanga',search:'Cuardaigh',tools:'Uirlisí',about:'Faoi',cancel:'Cealaigh',welcome:'Fáilte'}},
cy:{n:'Cymraeg',f:'🏴󠁧󠁢󠁷󠁬󠁳󠁿',s:{brand:'FomAI Office',tag:'Pecyn swyddfa yn y porwr',home:'Cartref',files:'Ffeiliau',create:'Creu',open:'Agor',save:'Cadw',close:'Cau',stng:'Gosodiadau',lang:'Iaith',search:'Chwilio',tools:'Offer',about:'Ynghylch',cancel:'Canslo',welcome:'Croeso'}},
mt:{n:'Malti',f:'🇲🇹',s:{brand:'FomAI Office',tag:'Pakkett tal-uffiċċju fil-browser',home:'Dar',files:'Fajls',create:'Oħloq',open:'Iftaħ',save:'Issejvja',close:'Agħlaq',stng:'Settings',lang:'Lingwa',search:'Fittex',tools:'Għodod',about:'Dwar',cancel:'Ikkanċella',welcome:'Merħba'}},
eu:{n:'Euskara',f:'🏴',s:{brand:'FomAI Office',tag:'Bulego-suite nabigatzailean',home:'Hasiera',files:'Fitxategiak',create:'Sortu',open:'Ireki',save:'Gorde',close:'Itxi',stng:'Ezarpenak',lang:'Hizkuntza',search:'Bilatu',tools:'Tresnak',about:'Honi buruz',cancel:'Utzi',welcome:'Ongi etorri'}},
ca:{n:'Català',f:'🏴',s:{brand:'FomAI Office',tag:"Paquet d'oficina al navegador",home:'Inici',files:'Fitxers',create:'Crea',open:'Obre',save:'Desa',close:'Tanca',stng:'Configuració',lang:'Idioma',search:'Cerca',tools:'Eines',about:'Quant a',cancel:'Cancel·la',welcome:'Benvingut'}},
gl:{n:'Galego',f:'🏴',s:{brand:'FomAI Office',tag:'Paquete de oficina no navegador',home:'Inicio',files:'Ficheiros',create:'Crear',open:'Abrir',save:'Gardar',close:'Pechar',stng:'Axustes',lang:'Idioma',search:'Buscar',tools:'Ferramentas',about:'Acerca de',cancel:'Cancelar',welcome:'Benvido'}},
es:{n:'Español',f:'🇪🇸',s:{brand:'FomAI Office',tag:'Suite de oficina en el navegador',home:'Inicio',files:'Archivos',create:'Crear',open:'Abrir',save:'Guardar',close:'Cerrar',stng:'Ajustes',lang:'Idioma',search:'Buscar',tools:'Herramientas',about:'Acerca de',cancel:'Cancelar',welcome:'Bienvenido'}},
pt:{n:'Português',f:'🇵🇹',s:{brand:'FomAI Office',tag:'Suíte de escritório no navegador',home:'Início',files:'Arquivos',create:'Criar',open:'Abrir',save:'Salvar',close:'Fechar',stng:'Configurações',lang:'Idioma',search:'Pesquisar',tools:'Ferramentas',about:'Sobre',cancel:'Cancelar',welcome:'Bem-vindo'}},
it:{n:'Italiano',f:'🇮🇹',s:{brand:'FomAI Office',tag:'Suite office nel browser',home:'Home',files:'File',create:'Crea',open:'Apri',save:'Salva',close:'Chiudi',stng:'Impostazioni',lang:'Lingua',search:'Cerca',tools:'Strumenti',about:'Informazioni',cancel:'Annulla',welcome:'Benvenuto'}},
fr:{n:'Français',f:'🇫🇷',s:{brand:'FomAI Office',tag:'Suite bureautique dans le navigateur',home:'Accueil',files:'Fichiers',create:'Créer',open:'Ouvrir',save:'Enregistrer',close:'Fermer',stng:'Paramètres',lang:'Langue',search:'Rechercher',tools:'Outils',about:'À propos',cancel:'Annuler',welcome:'Bienvenue'}},
oc:{n:'Occitan',f:'🏴',s:{brand:'FomAI Office',tag:'Burèu dins lo navegador',home:'Acuèlh',files:'Fichièrs',create:'Crear',open:'Dobrir',save:'Enregistrar',close:'Tampar',stng:'Paramètres',lang:'Lenga',search:'Recercar',tools:'Espleches',about:'A prepaus',cancel:'Anullar',welcome:'Benvengut'}},
co:{n:'Corsu',f:'🏴',s:{brand:'FomAI Office',tag:'Pacchettu d’uffiziu in u navigatore',home:'Casa',files:'Fiche',create:'Creà',open:'Apre',save:'Arregistrà',close:'Chjudè',stng:'Pparametri',lang:'Lingua',search:'Circà',tools:'Strumenti',about:'Di',cancel:'Annullà',welcome:'Benvenutu'}},
sc:{n:'Sardu',f:'🏴',s:{brand:'FomAI Office',tag:'Pachete de ufìtziu in su navigadore',home:'Acasagi',files:'Archìvios',create:'Crea',open:'Aberi',save:'Sarva',close:'Serra',stng:'Impostatziones',lang:'Lìngua',search:'Chirca',tools:'Ainas',about:'Subra',cancel:'Annulla',welcome:'Bene benidu'}},
rm:{n:'Rumantsch',f:'🇨🇭',s:{brand:'FomAI Office',tag:'Pachet d’uffizi en il navigatur',home:'Chasa',files:'Datotecas',create:'Crear',open:'Avrir',save:'Memorisar',close:'Serrar',stng:'Configuraziuns',lang:'Lingua',search:'Tschertgar',tools:'Utensils',about:'Davart',cancel:'Interrumper',welcome:'Bainvegni'}},
lb:{n:'Lëtzebuergesch',f:'🇱🇺',s:{brand:'FomAI Office',tag:'Office-Pak am Browser',home:'Haaptsäit',files:'Fichieren',create:'Erstellen',open:'Opmaachen',save:'Späicheren',close:'Zoumaachen',stng:'Astellungen',lang:'Sprooch',search:'Sichen',tools:'Wierkzei',about:'Iwwer',cancel:'Ofbriechen',welcome:'Wëllkomm'}},
fy:{n:'Frysk',f:'🏴',s:{brand:'FomAI Office',tag:'Kantoarpakket yn de browser',home:'Thús',files:'Bestannen',create:'Meitsje',open:'Iepenje',save:'Bewarje',close:'Slute',stng:'Ynstellings',lang:'Taal',search:'Sykje',tools:'Ark',about:'Oer',cancel:'Annulearje',welcome:'Wolkom'}},
fo:{n:'Føroyskt',f:'🇫🇴',s:{brand:'FomAI Office',tag:'Skrivstovupakki í kagranum',home:'Heim',files:'Fílur',create:'Ger',open:'Lat upp',save:'Goym',close:'Lat aftur',stng:'Stillingar',lang:'Mál',search:'Leita',tools:'Tól',about:'Um',cancel:'Angra',welcome:'Vælkomin'}},
yi:{n:'ייִדיש',f:'✡️',s:{brand:'FomAI Office',tag:'אָפֿיס פּאַקעט אין בראַוזער',home:'היים',files:'טעקעס',create:'שאַפֿן',open:'עפֿענען',save:'אויפֿהיטן',close:'פֿאַרמאַכן',stng:'איינשטעלונגען',lang:'שפּראַך',search:'זוכן',tools:'געצייג',about:'וועגן',cancel:'אַנולירן',welcome:'ברוכים הבאים'}},
la:{n:'Latina',f:'🏛️',s:{brand:'FomAI Office',tag:'Officium in navigatro',home:'Domus',files:'Fasciculi',create:'Creare',open:'Aperire',save:'Servare',close:'Claudere',stng:'Optiones',lang:'Lingua',search:'Quaerere',tools:'Instrumenta',about:'De',cancel:'Abrogare',welcome:'Salve'}},
eo:{n:'Esperanto',f:'🟢',s:{brand:'FomAI Office',tag:'Oficeja programaro en retumilo',home:'Hejmo',files:'Dosieroj',create:'Krei',open:'Malfermi',save:'Konservi',close:'Fermi',stng:'Agordoj',lang:'Lingvo',search:'Serĉi',tools:'Iloj',about:'Pri',cancel:'Nuligi',welcome:'Bonvenon'}},
he:{n:'עברית',f:'🇮🇱',s:{brand:'FomAI Office',tag:'חבילת משרד בדפדפן',home:'בית',files:'קבצים',create:'צור',open:'פתח',save:'שמור',close:'סגור',stng:'הגדרות',lang:'שפה',search:'חיפוש',tools:'כלים',about:'אודות',cancel:'ביטול',welcome:'ברוך הבא'}},
ar:{n:'العربية',f:'🇸🇦',s:{brand:'FomAI Office',tag:'حزمة مكتبية في المتصفح',home:'الرئيسية',files:'الملفات',create:'إنشاء',open:'فتح',save:'حفظ',close:'إغلاق',stng:'الإعدادات',lang:'اللغة',search:'بحث',tools:'الأدوات',about:'حول',cancel:'إلغاء',welcome:'مرحبا'}},
fa:{n:'فارسی',f:'🇮🇷',s:{brand:'FomAI Office',tag:'بسته اداری در مرورگر',home:'خانه',files:'فایل‌ها',create:'ایجاد',open:'باز کردن',save:'ذخیره',close:'بستن',stng:'تنظیمات',lang:'زبان',search:'جستجو',tools:'ابزارها',about:'درباره',cancel:'انصراف',welcome:'خوش آمدید'}},
ur:{n:'اردو',f:'🇵🇰',s:{brand:'FomAI Office',tag:'براؤزر میں آفس سوٹ',home:'ہوم',files:'فائلیں',create:'بنائیں',open:'کھولیں',save:'محفوظ کریں',close:'بند کریں',stng:'ترتیبات',lang:'زبان',search:'تلاش',tools:'اوزار',about:'کے بارے میں',cancel:'منسوخ',welcome:'خوش آمدید'}},
ps:{n:'پښتو',f:'🇦🇫',s:{brand:'FomAI Office',tag:'په براوزر کې دفتر پیکج',home:'کور',files:'فایلونه',create:'جوړول',open:'پرانیستل',save:'خوندي کول',close:'بندول',stng:'تنظیمات',lang:'ژبه',search:'لټون',tools:'وسایل',about:'په اړه',cancel:'لغوه',welcome:'ښه راغلاست'}},
ku:{n:'Kurdî',f:'🏴',s:{brand:'FomAI Office',tag:'Pakêta ofîsê di gerokê de',home:'Destpêk',files:'Pel',create:'Çêkirin',open:'Vekirin',save:'Tomar kirin',close:'Girtin',stng:'Mîheng',lang:'Ziman',search:'Lêgerîn',tools:'Amûr',about:'Derbarê',cancel:'Betal',welcome:'Bi xêr hatî'}},
sd:{n:'سنڌي',f:'🇵🇰',s:{brand:'FomAI Office',tag:'برائوزر ۾ آفيس سوٽ',home:'گھر',files:'فائلون',create:'ٺاهيو',open:'کوليو',save:'محفوظ ڪريو',close:'بند ڪريو',stng:'سيٽنگون',lang:'ٻولي',search:'ڳوليو',tools:'اوزار',about:'بابت',cancel:'منسوخ',welcome:'ڀلي ڪري آيا'}},
id:{n:'Bahasa Indonesia',f:'🇮🇩',s:{brand:'FomAI Office',tag:'Paket kantor di browser',home:'Beranda',files:'Berkas',create:'Buat',open:'Buka',save:'Simpan',close:'Tutup',stng:'Pengaturan',lang:'Bahasa',search:'Cari',tools:'Alat',about:'Tentang',cancel:'Batal',welcome:'Selamat datang'}},
ms:{n:'Bahasa Melayu',f:'🇲🇾',s:{brand:'FomAI Office',tag:'Pakej pejabat dalam pelayar',home:'Utama',files:'Fail',create:'Cipta',open:'Buka',save:'Simpan',close:'Tutup',stng:'Tetapan',lang:'Bahasa',search:'Cari',tools:'Alat',about:'Perihal',cancel:'Batal',welcome:'Selamat datang'}},
tl:{n:'Tagalog',f:'🇵🇭',s:{brand:'FomAI Office',tag:'Office suite sa browser',home:'Home',files:'Mga file',create:'Gumawa',open:'Buksan',save:'I-save',close:'Isara',stng:'Mga setting',lang:'Wika',search:'Maghanap',tools:'Mga tool',about:'Tungkol',cancel:'Kanselahin',welcome:'Maligayang pagdating'}},
vi:{n:'Tiếng Việt',f:'🇻🇳',s:{brand:'FomAI Office',tag:'Bộ văn phòng trong trình duyệt',home:'Trang chủ',files:'Tệp',create:'Tạo',open:'Mở',save:'Lưu',close:'Đóng',stng:'Cài đặt',lang:'Ngôn ngữ',search:'Tìm kiếm',tools:'Công cụ',about:'Giới thiệu',cancel:'Hủy',welcome:'Chào mừng'}},
th:{n:'ไทย',f:'🇹🇭',s:{brand:'FomAI Office',tag:'ชุดออฟฟิศในเบราว์เซอร์',home:'หน้าแรก',files:'ไฟล์',create:'สร้าง',open:'เปิด',save:'บันทึก',close:'ปิด',stng:'การตั้งค่า',lang:'ภาษา',search:'ค้นหา',tools:'เครื่องมือ',about:'เกี่ยวกับ',cancel:'ยกเลิก',welcome:'ยินดีต้อนรับ'}},
lo:{n:'ລາວ',f:'🇱🇦',s:{brand:'FomAI Office',tag:'ຊຸດຫ້ອງການໃນເບຣົາເຊີ',home:'ໜ້າຫຼັກ',files:'ໄຟລ໌',create:'ສ້າງ',open:'ເປີດ',save:'ບັນທຶກ',close:'ປິດ',stng:'ການຕັ້ງຄ່າ',lang:'ພາສາ',search:'ຄົ້ນຫາ',tools:'ເຄື່ອງມື',about:'ກ່ຽວກັບ',cancel:'ຍົກເລີກ',welcome:'ຍິນດີຕ້ອນຮັບ'}},
km:{n:'ខ្មែរ',f:'🇰🇭',s:{brand:'FomAI Office',tag:'កញ្ចប់ការិយាល័យក្នុងកម្មវិធីរុករក',home:'ដើម',files:'ឯកសារ',create:'បង្កើត',open:'បើក',save:'រក្សាទុក',close:'បិទ',stng:'ការកំណត់',lang:'ភាសា',search:'ស្វែងរក',tools:'ឧបករណ៍',about:'អំពី',cancel:'បោះបង់',welcome:'សូមស្វាគមន៍'}},
my:{n:'မြန်မာ',f:'🇲🇲',s:{brand:'FomAI Office',tag:'ဘရောက်ဇာတွင် ရုံးသုံးအစုံ',home:'ပင်မ',files:'ဖိုင်များ',create:'ဖန်တီး',open:'ဖွင့်',save:'သိမ်း',close:'ပိတ်',stng:'ဆက်တင်',lang:'ဘာသာ',search:'ရှာ',tools:'ကိရိယာ',about:'အကြောင်း',cancel:'ပယ်ဖျက်',welcome:'ကြိုဆိုပါတယ်'}},
zh:{n:'中文',f:'🇨🇳',s:{brand:'FomAI Office',tag:'浏览器办公套件',home:'主页',files:'文件',create:'新建',open:'打开',save:'保存',close:'关闭',stng:'设置',lang:'语言',search:'搜索',tools:'工具',about:'关于',cancel:'取消',welcome:'欢迎'}},
ja:{n:'日本語',f:'🇯🇵',s:{brand:'FomAI Office',tag:'ブラウザで使えるオフィススイート',home:'ホーム',files:'ファイル',create:'作成',open:'開く',save:'保存',close:'閉じる',stng:'設定',lang:'言語',search:'検索',tools:'ツール',about:'このアプリについて',cancel:'キャンセル',welcome:'ようこそ'}},
ko:{n:'한국어',f:'🇰🇷',s:{brand:'FomAI Office',tag:'브라우저 오피스 스위트',home:'홈',files:'파일',create:'만들기',open:'열기',save:'저장',close:'닫기',stng:'설정',lang:'언어',search:'검색',tools:'도구',about:'정보',cancel:'취소',welcome:'환영합니다'}},
hi:{n:'हिन्दी',f:'🇮🇳',s:{brand:'FomAI Office',tag:'ब्राउज़र में ऑफिस सूट',home:'होम',files:'फ़ाइलें',create:'बनाएँ',open:'खोलें',save:'सहेजें',close:'बंद करें',stng:'सेटिंग्स',lang:'भाषा',search:'खोजें',tools:'उपकरण',about:'परिचय',cancel:'रद्द करें',welcome:'स्वागत है'}},
bn:{n:'বাংলা',f:'🇧🇩',s:{brand:'FomAI Office',tag:'ব্রাউজারে অফিস স্যুট',home:'হোম',files:'ফাইল',create:'তৈরি',open:'খুলুন',save:'সংরক্ষণ',close:'বন্ধ',stng:'সেটিংস',lang:'ভাষা',search:'খুঁজুন',tools:'সরঞ্জাম',about:'সম্পর্কে',cancel:'বাতিল',welcome:'স্বাগতম'}},
ta:{n:'தமிழ்',f:'🇮🇳',s:{brand:'FomAI Office',tag:'உலாவியில் அலுவலக தொகுப்பு',home:'முகப்பு',files:'கோப்புகள்',create:'உருவாக்கு',open:'திற',save:'சேமி',close:'மூடு',stng:'அமைப்புகள்',lang:'மொழி',search:'தேடு',tools:'கருவிகள்',about:'பற்றி',cancel:'ரத்து',welcome:'வரவேற்கிறோம்'}},
te:{n:'తెలుగు',f:'🇮🇳',s:{brand:'FomAI Office',tag:'బ్రౌజర్‌లో కార్యాలయ సూట్',home:'హోమ్',files:'ఫైళ్లు',create:'సృష్టించు',open:'తెరువు',save:'సేవ్',close:'మూసివేయి',stng:'సెట్టింగ్‌లు',lang:'భాష',search:'వెతుకు',tools:'సాధనాలు',about:'గురించి',cancel:'రద్దు',welcome:'స్వాగతం'}},
ml:{n:'മലയാളം',f:'🇮🇳',s:{brand:'FomAI Office',tag:'ബ്രൗസറിൽ ഓഫീസ് സ്യൂട്ട്',home:'ഹോം',files:'ഫയലുകൾ',create:'സൃഷ്ടിക്കുക',open:'തുറക്കുക',save:'സേവ്',close:'അടയ്ക്കുക',stng:'ക്രമീകരണങ്ങൾ',lang:'ഭാഷ',search:'തിരയുക',tools:'ഉപകരണങ്ങൾ',about:'കുറിച്ച്',cancel:'റദ്ദാക്കുക',welcome:'സ്വാഗതം'}},
kn:{n:'ಕನ್ನಡ',f:'🇮🇳',s:{brand:'FomAI Office',tag:'ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಕಚೇರಿ ಸೂಟ್',home:'ಮುಖಪುಟ',files:'ಫೈಲ್‌ಗಳು',create:'ರಚಿಸಿ',open:'ತೆರೆಯಿರಿ',save:'ಉಳಿಸಿ',close:'ಮುಚ್ಚಿ',stng:'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',lang:'ಭಾಷೆ',search:'ಹುಡುಕಿ',tools:'ಪರಿಕರಗಳು',about:'ಬಗ್ಗೆ',cancel:'ರದ್ದುಮಾಡಿ',welcome:'ಸ್ವಾಗತ'}},
mr:{n:'मराठी',f:'🇮🇳',s:{brand:'FomAI Office',tag:'ब्राउझरमध्ये कार्यालय संच',home:'मुख्यपृष्ठ',files:'फाइल्स',create:'तयार करा',open:'उघडा',save:'जतन करा',close:'बंद करा',stng:'सेटिंग्ज',lang:'भाषा',search:'शोधा',tools:'साधने',about:'बद्दल',cancel:'रद्द',welcome:'स्वागत'}},
gu:{n:'ગુજરાતી',f:'🇮🇳',s:{brand:'FomAI Office',tag:'બ્રાઉઝરમાં ઓફિસ સ્યુટ',home:'હોમ',files:'ફાઇલો',create:'બનાવો',open:'ખોલો',save:'સાચવો',close:'બંધ કરો',stng:'સેટિંગ્સ',lang:'ભાષા',search:'શોધો',tools:'સાધનો',about:'વિશે',cancel:'રદ કરો',welcome:'સ્વાગત'}},
pa:{n:'ਪੰਜਾਬੀ',f:'🇮🇳',s:{brand:'FomAI Office',tag:'ਬਰਾਊਜ਼ਰ ਵਿੱਚ ਆਫਿਸ ਸੂਟ',home:'ਘਰ',files:'ਫਾਈਲਾਂ',create:'ਬਣਾਓ',open:'ਖੋਲ੍ਹੋ',save:'ਸੰਭਾਲੋ',close:'ਬੰਦ ਕਰੋ',stng:'ਸੈਟਿੰਗਾਂ',lang:'ਭਾਸ਼ਾ',search:'ਖੋਜੋ',tools:'ਸਾਧਨ',about:'ਬਾਰੇ',cancel:'ਰੱਦ',welcome:'ਜੀ ਆਇਆਂ ਨੂੰ'}},
or:{n:'ଓଡ଼ିଆ',f:'🇮🇳',s:{brand:'FomAI Office',tag:'ବ୍ରାଉଜରରେ ଅଫିସ ସୁଟ୍',home:'ହୋମ',files:'ଫାଇଲ୍',create:'ତିଆରି କରନ୍ତୁ',open:'ଖୋଲନ୍ତୁ',save:'ସଞ୍ଚୟ',close:'ବନ୍ଦ',stng:'ସେଟିଂସ୍',lang:'ଭାଷା',search:'ଖୋଜନ୍ତୁ',tools:'ସାଧନ',about:'ବିଷୟରେ',cancel:'ବାତିଲ୍',welcome:'ସ୍ୱାଗତ'}},
as:{n:'অসমীয়া',f:'🇮🇳',s:{brand:'FomAI Office',tag:'ব্ৰাউজাৰত অফিচ ছুইট',home:'হোম',files:'ফাইল',create:'সৃষ্টি কৰক',open:'খোলক',save:'ছেভ কৰক',close:'বন্ধ কৰক',stng:'ছেটিংছ',lang:'ভাষা',search:'সন্ধান কৰক',tools:'সঁজুলি',about:'বিষয়ে',cancel:'বাতিল',welcome:'স্বাগতম'}},
ne:{n:'नेपाली',f:'🇳🇵',s:{brand:'FomAI Office',tag:'ब्राउजरमा कार्यालय सूट',home:'गृह',files:'फाइलहरू',create:'सिर्जना',open:'खोल्नुहोस्',save:'सुरक्षित',close:'बन्द',stng:'सेटिङ',lang:'भाषा',search:'खोज्नुहोस्',tools:'उपकरण',about:'बारेमा',cancel:'रद्द',welcome:'स्वागत'}},
si:{n:'සිංහල',f:'🇱🇰',s:{brand:'FomAI Office',tag:'බ්‍රවුසරයේ කාර්යාල කට්ටලය',home:'මුල් පිටුව',files:'ගොනු',create:'සාදන්න',open:'විවෘත',save:'සුරකින්න',close:'වසන්න',stng:'සැකසුම්',lang:'භාෂාව',search:'සොයන්න',tools:'මෙවලම්',about:'ගැන',cancel:'අවලංගු',welcome:'සාදරයෙන් පිළිගනිමු'}},
sw:{n:'Kiswahili',f:'🇰🇪',s:{brand:'FomAI Office',tag:'Suite ya ofisi kwenye kivinjari',home:'Mwanzo',files:'Faili',create:'Unda',open:'Fungua',save:'Hifadhi',close:'Funga',stng:'Mipangilio',lang:'Lugha',search:'Tafuta',tools:'Zana',about:'Kuhusu',cancel:'Ghairi',welcome:'Karibu'}},
am:{n:'አማርኛ',f:'🇪🇹',s:{brand:'FomAI Office',tag:'በአሳሽ ውስጥ የቢሮ ስብስብ',home:'መነሻ',files:'ፋይሎች',create:'ፍጠር',open:'ክፈት',save:'አስቀምጥ',close:'ዝጋ',stng:'ቅንብሮች',lang:'ቋንቋ',search:'ፈልግ',tools:'መሳሪያዎች',about:'ስለ',cancel:'ሰርዝ',welcome:'እንኳን ደህና መጡ'}},
ha:{n:'Hausa',f:'🇳🇬',s:{brand:'FomAI Office',tag:'Kayan ofis a cikin burauza',home:'Gida',files:'Fayiloli',create:'Ƙirƙira',open:'Buɗe',save:'Ajiye',close:'Rufe',stng:'Saituna',lang:'Harshe',search:'Bincika',tools:'Kayan aiki',about:'Game da',cancel:'Soke',welcome:'Barka da zuwa'}},
yo:{n:'Yorùbá',f:'🇳🇬',s:{brand:'FomAI Office',tag:'Ẹ̀ka ọ́fíìsì nínú aṣàwákiri',home:'Ilé',files:'Àwọn fáìlì',create:'Ṣẹ̀dá',open:'Ṣí',save:'Pamọ́',close:'Pa',stng:'Ètò',lang:'Èdè',search:'Wá',tools:'Àwọn irinṣẹ́',about:'Nípa',cancel:'Fagilé',welcome:'Káàbọ̀'}},
ig:{n:'Igbo',f:'🇳🇬',s:{brand:'FomAI Office',tag:'Ngwugwu ọfịs na ihe nchọgharị',home:'Ụlọ',files:'Faịlụ',create:'Mepụta',open:'Mepee',save:'Chekwaa',close:'Mechie',stng:'Ntọala',lang:'Asụsụ',search:'Chọọ',tools:'Ngwaọrụ',about:'Banyere',cancel:'Kagbuo',welcome:'Nnọọ'}},
zu:{n:'isiZulu',f:'🇿🇦',s:{brand:'FomAI Office',tag:'Iphakethe lehhovisi kusiphequluli',home:'Ikhaya',files:'Amafayela',create:'Dala',open:'Vula',save:'Gcina',close:'Vala',stng:'Izilungiselelo',lang:'Ulimi',search:'Sesha',tools:'Amathuluzi',about:'Mayelana',cancel:'Khansela',welcome:'Siyakwamukela'}},
xh:{n:'isiXhosa',f:'🇿🇦',s:{brand:'FomAI Office',tag:'Iphakethe leofisi kwisiphequluli',home:'Ekhaya',files:'Iifayile',create:'Yenza',open:'Vula',save:'Gcina',close:'Vala',stng:'Iisetingi',lang:'Ulwimi',search:'Khangela',tools:'Izixhobo',about:'Malunga',cancel:'Rhoxisa',welcome:'Wamkelekile'}},
so:{n:'Soomaali',f:'🇸🇴',s:{brand:'FomAI Office',tag:'Xirmada xafiiska browser-ka',home:'Bogga hore',files:'Faylalka',create:'Abuur',open:'Fur',save:'Kaydi',close:'Xir',stng:'Dejinta',lang:'Luqadda',search:'Raadi',tools:'Qalabka',about:'Ku saabsan',cancel:'Jooji',welcome:'Ku soo dhawoow'}},
mg:{n:'Malagasy',f:'🇲🇬',s:{brand:'FomAI Office',tag:'Fitaovam-piasana ao amin’ny navigateur',home:'Fandraisana',files:'Rakitra',create:'Hamorona',open:'Sokafy',save:'Tehirizo',close:'Hidio',stng:'Kirakira',lang:'Fiteny',search:'Hikaroka',tools:'Fitaovana',about:'Mombamomba',cancel:'Foanana',welcome:'Tongasoa'}},

/* ═══════════════════ ШУТОЧНЫЕ ЯЗЫКИ (26) ═══════════════════ */

'x-hacker':{n:'Хакерский',f:'💻',s:{brand:'F0m41 0ff1c3',tag:'0ф1с п4к3т в 6р4уз3р3',home:'Гл4вн4я',files:'Ф4йлы',create:'С0зд4ть',open:'0ткр',save:'С0хр4н1ть',close:'3акрыть',stng:'Н4стр0йк1',lang:'Я3ык',search:'П01ск',tools:'1нстр',about:'0 пр03кт3',cancel:'0тм3н4',welcome:'Д06р0 п0ж4л0в4ть'}},
'x-leet':{n:'L33t 5p34k',f:'🔡',s:{brand:'F0m41 0ff1c3',tag:'0ff1c3 5u1t3 1n br0w53r',home:'H0m3',files:'F1l35',create:'Cr34t3',open:'0p3n',save:'54v3',close:'Cl053',stng:'53tt1ng5',lang:'L4ngu4g3',search:'53arch',tools:'700l5',about:'4b0u7',cancel:'C4nc3l',welcome:'w3lc0m3'}},
'x-code':{n:'Программистский',f:'🧑‍💻',s:{brand:'FomAI.Office',tag:'createOfficePackage({in:"browser"})',home:'renderHome()',files:'getFiles()',create:'create()',open:'open()',save:'save()',close:'close()',stng:'settings{}',lang:'locale.lang',search:'find()',tools:'tools[]',about:'about()',cancel:'reject()',welcome:'console.log("Hello, World!")'}},
'x-pre-rev':{n:'Дореволюціонный',f:'📜',s:{brand:'FomAI Office',tag:'Офісный пакетъ въ браузерѣ',home:'Главная',files:'Файлы',create:'Создать',open:'Открыть',save:'Сохранить',close:'Закрыть',stng:'Настройки',lang:'Языкъ',search:'Поискъ',tools:'Инструменты',about:'О проектѣ',cancel:'Отмѣна',welcome:'Добро пожаловать'}},
'x-soviet':{n:'Совѣтскій',f:'☭',s:{brand:'FomAI Office',tag:'Офисный пакет товарища',home:'Главная',files:'Файлы',create:'Создать',open:'Открыть',save:'Сохранить',close:'Закрыть',stng:'Настройки',lang:'Язык',search:'Поиск',tools:'Инструменты',about:'О проекте',cancel:'Отмена',welcome:'Товарищ! Добро пожаловать в строй!'}},
'x-pirate':{n:'Пиратский',f:'🏴‍☠️',s:{brand:'FomAI Office',tag:'Офисный сундук в браузере, йо-хо-хо!',home:'Каюта',files:'Сундуки',create:'Смастерить',open:'Открыть',save:'Припрятать',close:'Захлопнуть',stng:'Настройки корсара',lang:'Морской язык',search:'Рыскать',tools:'Снасти',about:'Про корабль',cancel:'Отбой',welcome:'Йо-хо-хо, салага!'}},
'x-yoda':{n:'Йода',f:'👽',s:{brand:'FomAI Office',tag:'В браузере офисный пакет, да',home:'Главная',files:'Файлы, да',create:'Создать',open:'Открыть',save:'Сохранить',close:'Закрыть, ммм',stng:'Настройки',lang:'Язык',search:'Искать',tools:'Инструменты',about:'О проекте',cancel:'Отмена',welcome:'Приветствую тебя, юный падаван'}},
'x-lolcat':{n:'Lolcat',f:'🐱',s:{brand:'FomAI Office',tag:'Werk in ur browser',home:'Homez',files:'Filez',create:'Mek',open:'Opun',save:'Sav',close:'Cloze',stng:'Settingz',lang:'Langwij',search:'Serch',tools:'Tooolz',about:'Abut',cancel:'Nevamind',welcome:'Hi u!'}},
'x-uwu':{n:'UwU',f:'🥺',s:{brand:'FomAI Office',tag:'UwU офисный пакетик >w<',home:'Дом-кун',files:'Файлик-тян',create:'Создать :3',open:'Откwыть',save:'Сохранить uwu',close:'Закwыть',stng:'Настwойки',lang:'Язычок',search:'Поиск~',tools:'Инстwументы',about:'О проекте >w<',cancel:'Отмена ня',welcome:'Пwивет, ня!'}},
'x-shakespeare':{n:'Шекспировский',f:'🎭',s:{brand:'FomAI Office',tag:'An office suite within thy browser',home:'Home',files:'Files',create:'Create',open:'Open',save:'Save',close:'Close',stng:'Settings',lang:'Tongue',search:'Seek',tools:'Tools',about:'Of this project',cancel:'Forsake',welcome:'Hail and well met!'}},
'x-polit':{n:'Депутатский',f:'🎩',s:{brand:'FomAI Office',tag:'Уважаемые коллеги, офисный пакет в браузере',home:'Главная',files:'Файлы',create:'Создать',open:'Открыть',save:'Сохранить',close:'Закрыть',stng:'Настройки',lang:'Язык',search:'Поиск',tools:'Инструменты',about:'О проекте',cancel:'Отмена',welcome:'Уважаемые граждане!'}},
'x-biznes':{n:'Деловой',f:'💼',s:{brand:'FomAI Office',tag:'Синергия офисных решений в браузере',home:'Дашборд',files:'Документооборот',create:'Сформировать',open:'Открыть',save:'Зафиксировать',close:'Завершить сессию',stng:'Конфигурация',lang:'Локаль',search:'Глубокий поиск',tools:'Инструментарий',about:'О компании',cancel:'Прервать',welcome:'Добро пожаловать в корпоративную экосистему'}},
'x-pushkin':{n:'Пушкинский',f:'🖋️',s:{brand:'FomAI Office',tag:'Офис в браузере, как в сказке',home:'Главная',files:'Файлы',create:'Создать',open:'Открыть',save:'Сохранить',close:'Закрыть',stng:'Настройки',lang:'Язык',search:'Поиск',tools:'Инструменты',about:'О проекте',cancel:'Отмена',welcome:'Мороз и солнце; день чудесный!'}},
'x-binary':{n:'Двоичный',f:'0️⃣',s:{brand:'01000110 01101111 01101101 01000001 01001001',tag:'01001111 01100110 01100110 01101001 01100011 01100101',home:'01001000 01101111 01101101 01100101',files:'01000110 01101001 01101100 01100101 01110011',create:'01000011 01110010 01100101 01100001 01110100 01100101',open:'01001111 01110000 01100101 01101110',save:'01010011 01100001 01110110 01100101',close:'01000011 01101100 01101111 01110011 01100101',stng:'01010011 01100101 01110100 01110100 01101001 01101110 01100111 01110011',lang:'01001100 01100001 01101110 01100111',search:'01010011 01100101 01100001 01110010 01100011 01101000',tools:'01010100 01101111 01101111 01101100 01110011',about:'01000001 01100010 01101111 01110101 01110100',cancel:'01000011 01100001 01101110 01100011 01100101 01101100',welcome:'01010111 01100101 01101100 01100011 01101111 01101101 01100101'}},
'x-morse':{n:'Морзянка',f:'📡',s:{brand:'..-. --- -- .- .. / --- ..-. ..-. .. -.-. .',tag:'--- ..-. ..-. .. -.-. . / ... ..- .. - .',home:'.... --- -- .',files:'..-. .. .-.. . ...',create:'-.-. .-. . .- - .',open:'--- .--. . -.',save:'... .- ...- .',close:'-.-. .-.. --- ... .',stng:'... . - - .. -. --. ...',lang:'.-.. .- -. --.',search:'... . .- .-. -.-. ....',tools:'- --- --- .-.. ...',about:'.- -... --- ..- -',cancel:'-.-. .- -. -.-. . .-..',welcome:'.-- . .-.. -.-. --- -- .'}},
'x-rot13':{n:'ROT13',f:'🔄',s:{brand:'SbZN V Bssvpr',tag:'Bssvpr fhvgr va oebjfre',home:'Ubzr',files:'Svyrf',create:'Perngr',open:'Bcra',save:'Fnir',close:'Pybfr',stng:'Frggvatf',lang:'Ynathntr',search:'Frneup',tools:'Gbbyf',about:'Nobhg',cancel:'Pnapry',welcome:'Jrypbzr'}},
'x-reverse':{n:'Обратный',f:'⬅️',s:{brand:'eciffO IAmof',tag:'ерезаурб в текап йынсaфO',home:'яанвлaГ',files:'ылыaФ',create:'ьтадзoС',open:'ытькрO',save:'ытьнархoС',close:'ытькрыЗ',stng:'икйoртсaН',lang:'кыЗ',search:'ксoП',tools:'ытнемуртснИ',about:'етoерп O',cancel:'анемO',welcome:'ьтевoлaжoп oрoбoД'}},
'x-emoji':{n:'Эмодзи',f:'😀',s:{brand:'F📝AI🏢',tag:'🏢📦🌐',home:'🏠',files:'📁',create:'✨',open:'📂',save:'💾',close:'✖️',stng:'⚙️',lang:'🌍',search:'🔍',tools:'🛠️',about:'ℹ️',cancel:'❌',welcome:'👋😊'}},
'x-gibber':{n:'Абракадабра',f:'🌀',s:{brand:'ФомАЙ Офыс',tag:'Офысный пикед в бракызере',home:'Глакная',files:'Файлыки',create:'Создурачить',open:'Открывашка',save:'Схорон',close:'Закрывашка',stng:'Настроечки',lang:'Язык-мурык',search:'Поискунчик',tools:'Инструментики',about:'Про проект-мурлект',cancel:'Отменик',welcome:'Добро потопали!'}},
'x-klingon':{n:'Клингонский',f:'🖖',s:{brand:'FomAI wa\' Office',tag:'QonoS paq pa\' browser',home:'juH',files:'ghItlhmey',create:'chu\'',open:'poSmoH',save:'choq',close:'SoQmoH',stng:'SeHmey',lang:'Hol',search:'Sam',tools:'janmey',about:'’oH',cancel:'QIl',welcome:'nuqneH!'}},
'x-dovah':{n:'Драконий',f:'🐉',s:{brand:'FomAI Office',tag:'Ofis fah browser',home:'Hofkiin',files:'Fahdon',create:'Kren',open:'Nid',save:'Koraav',close:'Nahl',stng:'Rii',lang:'Tinvaak',search:'Rot',tools:'Gut',about:'Pruzah',cancel:'Niid',welcome:'Drem Yol Lok!'}},
'x-ferb':{n:'Ферб-латынь',f:'🥴',s:{brand:'OmAI-Fay Ofiice-ay',tag:'Ofiice-ay uite-say in-ay owser-bray',home:'Ome-hay',files:'Iles-fay',create:'Eate-cray',open:'Open-ay',save:'Ave-say',close:'Ose-clay',stng:'Ettings-say',lang:'Anguage-lay',search:'Earch-say',tools:'Ools-tay',about:'About-ay',cancel:'Ancel-cay',welcome:'Elcome-way!'}},
'x-corp':{n:'Корпоративный',f:'🏢',s:{brand:'FomAI Office Enterprise',tag:'Синергия офисных решений',home:'Дашборд',files:'Ресурсы',create:'Инициировать',open:'Запустить',save:'Коммит',close:'Завершить',stng:'Конфигурация',lang:'Локаль',search:'Аналитика',tools:'Модули',about:'О компании',cancel:'Прервать процесс',welcome:'Добро пожаловать в нашу экосистему'}},
'x-hipster':{n:'Хипстер',f:'🧔',s:{brand:'FomAI Office (ты не слышал)',tag:'Офисный стартап до того, как это стало мейнстримом',home:'Базовый',files:'Ассеты',create:'Сгенерь',open:'Задеплой',save:'Запушь',close:'Архивируй',stng:'Настройки (не для всех)',lang:'Локаль (андеграунд)',search:'Скаутинг',tools:'Тулки',about:'Манифест',cancel:'Не сейчас',welcome:'Йо, ты в теме'}},
'x-boomer':{n:'Бумер',f:'👴',s:{brand:'ФомАЙ Офис',tag:'В наше время всё было проще',home:'Дом',files:'Документы',create:'Создать',open:'Открыть',save:'Сохранить',close:'Закрыть',stng:'Настройки',lang:'Язык',search:'Найти',tools:'Инструменты',about:'О проекте',cancel:'Отмена',welcome:'Здравствуйте, молодой человек!'}},
'x-minion':{n:'Миньонский',f:'🍌',s:{brand:'FomAI Office banana!',tag:'Bello! Office in browser!',home:'Bello',files:'Poka-files',home:'Bello',files:'Poka-files',create:'Bee-do!',open:'Poka!',save:'Papoy!',close:'Poopaye!',stng:'Tulaliloo',lang:'Banana',search:'Bapple',tools:'Gelato',about:'Para tú',cancel:'Me want banana',welcome:'Bello, banana!'}},
'x-cat':{n:'Кошачий',f:'😺',s:{brand:'ФомАЙ Мяу-с',tag:'Мяу-офис в мяу-браузере',home:'Мяу-главная',files:'Мяу-файлы',create:'Мяу-создать',open:'Мяу-открыть',save:'Мяу-сохранить',close:'Мяу-закрыть',stng:'Мяу-настройки',lang:'Мяу-язык',search:'Мяу-поиск',tools:'Мяу-инструменты',about:'Мяу-про-проект',cancel:'Мяу-отмена',welcome:'Мяу! (≽^•⩊•^≼)'}},
'x-drunk':{n:'Пьяный',f:'🍺',s:{brand:'Фом-А-Ай Офисс',tag:'Офысный пакед в б-браузере, ик',home:'Глав-на-я',files:'Файлы, ик',create:'Соз-да-ать',open:'Аткрыть',save:'С-сахранить',close:'Закры-ыть',stng:'Настро-ойки',lang:'Язы-ык',search:'Па-иск',tools:'Инстру-ументы',about:'О про-оекте',cancel:'Атме-ена',welcome:'Добро пож-жаловать, ик!'}}

;